FROM dsavell/minideb-nginx:1.20.1-1

RUN \
  install_packages \
    nano \
    cron && \
  ## Download GRAV
  mkdir -p \
    /grav && \
  GRAV_VERSION=$(curl -sX GET "https://api.github.com/repos/getgrav/grav/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]') && \
  curl -o /grav/grav.zip -L https://github.com/getgrav/grav/releases/download/${GRAV_VERSION}/grav-v${GRAV_VERSION}.zip

COPY root/ /

WORKDIR /config/www

CMD ["/init-core"]
