---
name: Build

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GRAV Version
        run: |
          GRAV_VERSION=$(curl -sL "https://api.github.com/repos/getgrav/grav/releases/latest" | grep tag_name | cut -d '"' -f 4)
          echo "${GRAV_VERSION}"
          echo "GRAV_VERSION=${GRAV_VERSION}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Build
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          platforms: linux/${{ matrix.platform }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ github.run_id }}:${{ matrix.platform }}
          build-args: |
            GRAV_VERSION=${{ env.GRAV_VERSION }}

      - name: Docker - Run
        run: |
          docker run -d \
            --name=grav_test \
            -p 127.0.0.1:80:80/tcp \
            --env-file .env.example \
            -v ./grav/backup:/grav/backup \
            -v ./grav/user:/grav/user \
            ${{ github.run_id }}:${{ matrix.platform }}

      - name: Test - Listening Port 80
        run: |
          sleep 5s
          nc -z -v 127.0.0.1 80 || exit 1

      - name: Test - Webpage access
        run: |
          sleep 20s
          if curl -v --silent 127.0.0.1:80/admin | grep Grav; then
            echo "Grav webpage accessible"
          else
            exit 2
          fi

      - name: Test - Update plugins function
        run: |
          if docker exec grav_test update-plugins | grep 'Nothing to update'; then
            echo "Grav update plugins function OK"
          else
            exit 3
          fi

      - name: Test - Backup function
        run: |
          if docker exec grav_test backup | grep 'Backup Successfully Created'; then
            echo "Grav backup successfull"
          else
            exit 4
          fi
