---
name: Release

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 1 * * *' # Everyday at 01:00am
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Date
        run: |
          DATE=$(date +"%Y%m%d")
          echo "${DATE}"
          echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: Get GRAV Version
        run: |
          GRAV_VERSION=$(curl -sL "https://api.github.com/repos/getgrav/grav/releases/latest" | grep tag_name | cut -d '"' -f 4)
          echo "${GRAV_VERSION}"
          echo "GRAV_VERSION=${GRAV_VERSION}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker Metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            dsavell/grav
            ghcr.io/dsavell/grav
          tags: |
            type=raw,value=${{ env.GRAV_VERSION }}
            type=raw,value=${{ env.GRAV_VERSION }}-${{ env.DATE }}

      - name: Docker - Build & Push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          build-args: |
            GRAV_VERSION=${{ env.GRAV_VERSION }}
